### ISSUE TITLE
Could keepass2 directly  run on Linux, MAC OS using mono?

### ISSUE THREAD

**Issue by cxueqin** [cappert/keepass2#3]
Hi @cappert 

Thank your for manually mirror keepass2 project. Since keepass2 is csharp based, so can it run on non-windows platform such as linux, mac osx? If it's supported, that will be very friendly to users.

**Comment by cappert** [comment]
yes, see http://keepass.info/help/v2/setup.html#mono

personally I prefer using KeePassX on Linux/OS X.
